name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    - name: Build with Gradle
        run: ./xic-build
    - name: Upload a JAR Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: xi-compiler-jar
        # A file, directory or wildcard pattern that describes what to upload
        path: build/lib/all-in-one-jar-1.0-SNAPSHOT.jar
    - name: Upload a EXE Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: xi-compiler-exe
        path: xic

